import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import ThemeWrapper from "./theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeToggle } from "./(routes)/dashboard/_components/ThemeToggle";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PictelAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Provider>
          <ThemeWrapper>
            {children}
            <Toaster/>
             <div className="fixed bottom-4 right-4 z-50">
    <ThemeToggle />
  </div>
          </ThemeWrapper>
        </Provider>
      </body>
    </html>
  );
}
